# Use the official Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Install FFmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg

# Expose the port the server runs on
EXPOSE 5000

# Command to run the server
CMD ["node", "server.js"]